server:
  port: 4000
  servlet:
    session.cookie.name: b8a5f3fb

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: ${ddl.auto}

  # 레디스 설정
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB

# 로깅 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

# 파일 업로드 경로 설정
file:
  upload:
    url: ${file.url}
    path: ${file.path}


# 파이썬 설정
python:
  path:
    base: ${python.base}
    base2: ${python.base2}
    trend: ${python.trend}
    restaurant: ${python.restaurant}

springdoc:
  version: '1.0.0'
  api-docs:
    path: /docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**
  member:
    jwt:
      secret: ${jwt.secret}
      validTime: ${jwt.validTime}

# 소셜 로그인 API 설정
social:
  kakao.apikey: ${kakao.apikey}